version: "3.8"

services:
  api-gateway:
    build: ./src/api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./src/api-gateway/.env

  authentication:
    build: ./src/services/authentication-service
    ports:
      - "3001:3001"
    env_file:
      - ./src/services/authentication-service/.env
    depends_on:
      - postgres

  events:
    build: ./src/services/events-service
    ports:
      - "3002:3002"
    env_file:
      - ./src/services/events-service/.env

  expenses:
    build: ./src/services/expenses-service
    ports:
      - "3003:3003"
    env_file:
      - ./src/services/expenses-service/.env

  notifications:
    build: ./src/services/notifications-service
    ports:
      - "3004:3004"
    env_file:
      - ./src/services/notifications-service/.env

  payments:
    build: ./src/services/payments-service
    ports:
      - "3005:3005"
    env_file:
      - ./src/services/payments-service/.env

  pgAdmin:
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "82:80"
      depends_on:
      - postgres

  # Add other services here with their respective build paths and port mappings
  postgres:
      image: postgres:15
      environment:
        POSTGRES_USER: payparty
        POSTGRES_PASSWORD: payparty
        POSTGRES_DB: payparty
      # ports:
      #   - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
